version: '3.5'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - "./data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_DATABASE: 'springcloud6'
    networks:
      - mysql


  eureka:
    image: dockerfatemeh/03eureka_server:test6
    container_name: eureka
    ports:
      - "8761:8761"
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker


  product:
    image: dockerfatemeh/01product:test6
    container_name: product6
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - spring
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka
      - mysql


  discount:
    image: dockerfatemeh/02discount:test6
    container_name: discount6
    ports:
      - "8086:8086"
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - spring
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka
      - mysql



  notification:
    image: dockerfatemeh/05notification:test6
    container_name: notification6
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - spring
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka
      - mysql



  apigetway:
    image: dockerfatemeh/06gateway_service:test6
    container_name: apigetway6
    ports:
      - "7070:7070"
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka

#  rabbitmq:
#    #image: rabbitmq:latest
#    image: rabbitmq:3.9.11-management-alpine
#    container_name: 'rabbitmq'
#    ports:
#      - 5672:5672
#      - 15672:15672
#    networks:
#      - spring

networks:
  default:
  spring:
    driver: bridge
  mysql:
    driver: bridge
#volumes:
#  my-datavolume:
