spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5




server:
  port: 7070
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true
    gateway:
      enabled: true
    health:
      show-details: always

  info:
    env:
      enabled: true
    health:
      probes:
        enabled: true




  health:
    circuitbreakers:
     enabled: true




info:
  app:
    name: "apigateway"
    description: " product micro api gateway"
    version: "1"



resilience4j.circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        allow-health-indicator-to-fail: false
        register-health-indicator: true