#logging:
#  level:
#    org.springframework.web: trace
#    org.springframework.jdbc.core: trace
#    org.springframework.data.jpa: trace
#    root: debug

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/springcloud6
    username: root
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: "false"

  application:
    name: notification

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5



server:
  port: 8082


#  main:
#    banner-mode: off