#logging:
#  level:
#    org.springframework.web: trace
#    org.springframework.jdbc.core: trace
#    org.springframework.data.jpa: trace
#    root: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud6
    username: root
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: "false"

  application:
    name: product

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  rabbitmq:
    addresses: localhost:5672

eureka:
# instance:
#   prefer-ip-address: false
#   lease-renewal-interval-in-seconds: 5
#   lease-expiration-duration-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    registry-fetch-interval-seconds: 5



management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true
    gateway:
      enabled: true
    health:
      show-details: always

  info:
    env:
      enabled: true
    health:
      probes:
        enabled: true




  health:
    circuitbreakers:
      enabled: true




info:
  app:
    name: "product"
    description: " product service"
    version: "1"




resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10000
      permitted-number-of-calls-in-half-open-state: 3
      automatic-transition-from-open-to-half-open-enabled: true
      allow-health-indicator-to-fail: false
      register-health-indicator: true

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 100
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
